from __future__ import annotations

from ..models import AnalysisReport, Finding

_SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]

_SEVERITY_BADGE = {
    "CRITICAL": "🔴 CRITICAL",
    "HIGH": "🟠 HIGH",
    "MEDIUM": "🟡 MEDIUM",
    "LOW": "🔵 LOW",
    "INFO": "⚪ INFO",
}

_RISK_BANNER = {
    "CRITICAL": "🚨",
    "HIGH": "⚠️",
    "MEDIUM": "🔶",
    "LOW": "✅",
}


def render(report: AnalysisReport) -> str:
    lines: list[str] = []

    ts = report.analyzed_at.strftime("%Y-%m-%d %H:%M UTC")
    banner = _RISK_BANNER.get(report.risk_level, "")

    lines += [
        "# SPECTRA — Security Intelligence Report",
        f"*Analyzed: {ts} | Scanner: {report.scanner_type}*",
        "",
        "---",
        "",
        f"## {banner} Overall Risk: {report.risk_level} &nbsp; `{report.overall_risk_score}/100`",
        "",
        "### Executive Summary",
        "",
        report.executive_summary,
        "",
    ]

    # ── Findings Summary ──────────────────────────────────────────────────────
    sev = report.findings_by_severity
    lines += [
        "### Findings at a Glance",
        "",
        "| Severity | Count |",
        "|:---------|------:|",
    ]
    for level in _SEVERITY_ORDER:
        count = getattr(sev, level, 0)
        badge = _SEVERITY_BADGE[level]
        lines.append(f"| {badge} | {count} |")

    meta = report.scan_metadata
    lines += [
        "",
        f"*{meta.total_raw_findings} raw findings → {meta.after_dedup} unique after dedup*",
        "",
        "---",
        "",
    ]

    # ── Immediate Actions ─────────────────────────────────────────────────────
    if report.immediate_actions:
        lines += ["## ⚡ Immediate Actions Required", ""]
        for i, action in enumerate(report.immediate_actions, 1):
            lines.append(f"{i}. {action}")
        lines.append("")

    # ── Attack Chains ─────────────────────────────────────────────────────────
    if report.attack_chains:
        lines += ["## 🔗 Attack Chains", ""]
        for chain in report.attack_chains:
            ids = ", ".join(f"`{fid}`" for fid in chain.finding_ids)
            lines += [
                f"### {chain.name}",
                f"*Chained findings: {ids}*",
                "",
                chain.description,
                "",
            ]

    # ── Detailed Findings ─────────────────────────────────────────────────────
    if report.findings:
        lines += ["## Detailed Findings", ""]
        sorted_findings = sorted(
            report.findings,
            key=lambda f: _SEVERITY_ORDER.index(f.severity),
        )
        for f in sorted_findings:
            lines += _render_finding(f)

    # ── Strategic Recommendations ─────────────────────────────────────────────
    if report.strategic_recommendations:
        lines += ["## Strategic Recommendations", ""]
        for rec in report.strategic_recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    lines += [
        "---",
        "*Report generated by [SPECTRA](https://github.com/spectra-security/spectra) · "
        "Powered by Claude Anthropic*",
    ]

    return "\n".join(lines)


def _render_finding(f: Finding) -> list[str]:
    badge = _SEVERITY_BADGE[f.severity]
    cvss_str = f"**CVSS:** `{f.cvss_score}`  |  " if f.cvss_score else ""
    lines = [
        f"### {badge} — {f.title} &nbsp; `{f.id}`",
        "",
        f"**Component:** `{f.affected_component}`  |  "
        f"{cvss_str}"
        f"**Exploitability:** {f.exploitability}",
        "",
        f"{f.description}",
        "",
        f"> **Remediation:** {f.remediation}",
        "",
    ]
    if f.references:
        lines.append("**References:**")
        for ref in f.references[:5]:
            lines.append(f"- {ref}")
        lines.append("")
    lines.append("")
    return lines
