import type { AnalysisReport } from '../types'
import RiskOverview from './RiskOverview'
import FindingsTable from './FindingsTable'
import AttackChains from './AttackChains'

interface ReportViewProps {
  report: AnalysisReport
  filename: string
  createdAt: string
}

function ImmediateActions({ actions }: { actions: string[] }) {
  if (actions.length === 0) return null
  return (
    <div className="card">
      <div className="card-header">
        <span className="section-label">Immediate Actions</span>
      </div>
      <ol className="px-5 py-4 space-y-3">
        {actions.map((action, i) => (
          <li key={i} className="flex items-start gap-3">
            <span className="shrink-0 flex items-center justify-center w-5 h-5 rounded-full bg-cyan-400/10 border border-cyan-400/30 text-cyan-400 text-xs font-bold mt-0.5">
              {i + 1}
            </span>
            <span className="text-sm text-slate-300 leading-relaxed">{action}</span>
          </li>
        ))}
      </ol>
    </div>
  )
}

function ExecutiveSummary({ summary }: { summary: string }) {
  return (
    <div className="card">
      <div className="card-header">
        <span className="section-label">Executive Summary</span>
      </div>
      <p className="px-5 py-4 text-sm text-slate-300 leading-relaxed">{summary}</p>
    </div>
  )
}

function StrategicRecommendations({ recs }: { recs: string[] }) {
  if (recs.length === 0) return null
  return (
    <div className="card">
      <div className="card-header">
        <span className="section-label">Strategic Recommendations</span>
      </div>
      <ul className="px-5 py-4 space-y-3">
        {recs.map((rec, i) => (
          <li key={i} className="flex items-start gap-3">
            <span className="shrink-0 w-1.5 h-1.5 rounded-full bg-slate-500 mt-2" />
            <span className="text-sm text-slate-300 leading-relaxed">{rec}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}

export default function ReportView({ report, filename, createdAt }: ReportViewProps) {
  const formattedDate = (() => {
    try { return new Date(createdAt).toLocaleString() } catch { return createdAt }
  })()

  return (
    <div className="flex flex-col gap-4 p-6 overflow-y-auto h-full">
      {/* Report header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-slate-100 tracking-tight">{filename}</h2>
          <p className="text-xs text-slate-500 mt-0.5">{formattedDate}</p>
        </div>
      </div>

      <RiskOverview report={report} />
      <ExecutiveSummary summary={report.executive_summary} />
      <ImmediateActions actions={report.immediate_actions} />
      {report.attack_chains.length > 0 && (
        <AttackChains chains={report.attack_chains} findings={report.findings} />
      )}
      <FindingsTable
        findings={report.findings}
        findingsBySeverity={report.findings_by_severity}
      />
      <StrategicRecommendations recs={report.strategic_recommendations} />

      <p className="text-center text-xs text-slate-700 py-2">
        Report generated by SPECTRA · Powered by Claude AI
      </p>
    </div>
  )
}
